name: Upload code coverage
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build
      - name: Setup dotCover
        run: dotnet tool install JetBrains.dotCover.GlobalTool -g
      - name: Setup coveralls-uploader
        run: dotnet tool install --global coveralls-uploader --version 0.1.0
      - name: Run dotCover coverage
        run: dotnet dotcover test --dcXML="dotcover.xml"
      - name: Conver to lcov format
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.0
        with:
          reports: coverage/code-coverage.xml
          targetdir: coverage
          reporttypes: lcov
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov.info
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Upload data to coveralls.io
        run: coveralls-uploader -i coverage/lcov.info -t DQyGHUKIznRy7m0DLDpiduTVFSeA9NQZE
