name: dotnet build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: dotnet build
    - name: Setup dotCover
      run: dotnet tool install JetBrains.dotCover.GlobalTool -g
    - name: Run dotCover coverage
      run: dotnet dotcover test --dcXML="dotcover.xml"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage/code-coverage.xml
      
        