name: Upload code coverage
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Setup dotCover
        run: dotnet tool install JetBrains.dotCover.GlobalTool -g
      - name: Setup coveralls-uploader
        run: dotnet tool install --global coveralls-uploader --version 0.6.6
      - name: Run dotCover coverage
        run: dotnet dotcover test --dcXML="dotcover.xml"
      - name: Conver to lcov format
        uses: danielpalme/ReportGenerator-GitHub-Action@5.0.0
        with:
          reports: coverage/code-coverage.xml
          targetdir: coverage
          reporttypes: lcov
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/lcov.info
      - name: Set pull request number
        if: github.event_name == 'pull_request'
        run: echo "COVERALLS_PULL_REQUEST_NUMBER=${{github.event.number}}" >> $GITHUB_ENV
      - name: Upload data to coveralls.io
        run: coveralls-uploader -i coverage/lcov.info -v
